{
 "title": "AI 分析應用服務",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "服務監控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "平均每分鐘使用次數 (次數/分)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(swot_predict_total{job=\"app_exporters\"}[1m]) * 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "平均每日資料異常次數",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "rate(swot_feature_drift_total{job=\"app_exporters\"}[12h]) * 60 * 60 * 24",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "商業價值計算",
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "(swot_predict_total) * 3 * (200/3600) * 0.8"
    }
   ]
  },
  {
   "title": "AI服務總使用次數",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "swot_predict_total" }
   ]
  },
  {
   "title": "資料品質偏差次數  (Feature drift)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "swot_feature_drift_total" }
   ]
  },
  {
   "title": "模型建模次數",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mlflow_num_of_run_exp" }
   ]
  },
  { "title": "服務容器監控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "容器啟動數量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{state=\"running\", job=\"docker_exporters\"}",
     "legendFormat": "{{instance}} {{state}}"
    }
   ]
  },
  {
   "title": "容器啟動數量",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_daemon_container_states_containers{job=\"docker_exporters\"}\r\n",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "網路狀態", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "服務狀態",
   "type": "state-timeline",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 29 },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}} ({{instance}})" }
   ]
  },
  {
   "title": "AI服務狀態",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 15, "x": 9, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "服務器硬體監控 (Hardware)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "HPC1 硬體資訊 (Digital Twin)",
   "type": "pierosavi-imageit-panel",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\"}[1m])) * 100)\r\n"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes{job=\"os_exporters\"}/1000000000"
    },
    {}
   ]
  },
  {
   "title": "CPU 使用率 (CPU Usage)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 43 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{mode=\"idle\",instance=\"10.55.23.101:9182\"}[1m])) * 100)",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "剩餘記憶體 (GB)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_os_physical_memory_free_bytes{job=\"os_exporters\",instance=\"10.55.23.101:9182\"}/1000000000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partitions Free Space",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_free_bytes{instance=\"10.55.23.101:9182\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{instance}} ( {{volume}} )",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  }
 ]
}